version: 0.2

env:
  variables:
    NEXT_PUBLIC_API_URL: https://api.yourdomain.com

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g npm@latest
  
  pre_build:
    commands:
      - echo Installing frontend dependencies...
      - cd frontend/customer-portal
      - npm ci
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the frontend application...
      - npm run build
  
  post_build:
    commands:
      - echo Running tests...
      - npm test -- --watchAll=false
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/customer-portal/.next'
  discard-paths: no